### ISSUE TITLE
Parallel passages extension

### ISSUE THREAD

**Issue by ryderwishart** [genesis-ai-dev/codex-editor#23]
We should leverage the copilot RAG index to reveal similar passages both in the translation draft and in the source text

- [x] Use two tabs ([panels](https://github.com/microsoft/vscode-webview-ui-toolkit/blob/main/src/panels/README.md) from web view ui toolkit), one for parallel passages as we have them now, and a second for Anomaly Detection
- [x] the Anomaly Detection tab reveals two lists of vrefs side-by-side (use 'flex' css for responsiveness), one under the "Your Draft" heading and another under "Source Text"
- [ ] ~~show three kinds of mismatches: order mismatch, missing verses or extra verses~~
- [ ] ~~use the combined greek/hebrew vref bible file for source text embeddings~~
- [x] if a verse hasn't been translated in the draft yet, then just grey it out from the results

Once we have this basic display working, let's try the following:
- [x] Detect anomalies in the editor itself using the language server

![Image](https://github.com/genesis-ai-dev/codex-editor/assets/19649268/0285a5f0-c72b-4b58-ba7b-5e720f1e7a37)

**Comment by dadukhankevin** [comment]
A couple of things I'm thinking about.
- I'm not sure if embeddings will be accurate enough for order mismatch to matter. We'll have to see.
- Does having this specific LAD on in the background all the time require too many resources? Switching databases, querying embeddings etc...

**Comment by ryderwishart** [comment]
The most pressing need for this feature is to improve the UI. Currently there are overflow problems, spacing issues (results take up lots of space), etc.
